name: api_project
description: A new Flutter project.


publish_to: 'none' 



version: 1.0.0+1

environment:
  sdk: '>=3.1.0-129.0.dev <4.0.0'







dependencies:
  flutter:
    sdk: flutter


  
  
  cupertino_icons: ^1.0.2
  flutter_dotenv: ^5.1.0
  get: ^4.6.5
  http: ^0.13.6
  http_interceptor: ^1.0.2
  jwt_decoder: ^2.0.1
  get_storage: ^2.1.1
  path_provider: ^2.0.15
  cached_network_image: ^3.2.3
  html: ^0.15.4
  syncfusion_flutter_charts: ^22.1.39
  syncfusion_flutter_gauges: ^22.1.39

dev_dependencies:
  flutter_test:
    sdk: flutter

  
  
  
  
  
  flutter_lints: ^2.0.0





flutter:

  
  
  
  uses-material-design: true
  assets:
    - .env
    - assets/Union.png
    - assets/popup.png

  
  
  
  

  
  

  
  

  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
